apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demo-ranker-tfidf-drones-en-dp
  namespace: stand-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-ranker-tfidf-drones-en-dp
    spec:
      containers:
      - name: demo-ranker-tfidf-drones-en
        image: kubeadm.ipavlov.mipt.ru:5000/demo/ranker_tfidf_drones_en
        ports:
        - name: cp6020
          protocol: TCP
          containerPort: 6020
        volumeMounts:
        - name: volume-logs
          mountPath: /logs
        - name: volume-podinfo
          mountPath: /etc/podinfo
          readOnly: false
        env:
        - name: POD_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumes:
      - name: volume-logs
        persistentVolumeClaim:
          claimName: logs-hostpath-pvc
      - name: volume-podinfo
        downwardAPI:
          items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
