apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demo-bhge-retrieval-tables-ensemble-dp
  namespace: stand-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-bhge-retrieval-tables-ensemble-dp
    spec:
      containers:
      - name: demo-bhge-retrieval-tables-ensemble
        image: kubeadm.ipavlov.mipt.ru:5000/demo/bhge_retrieval_tables_ensemble
        ports:
        - name: cp6023
          protocol: TCP
          containerPort: 6023
        volumeMounts:
        - name: volume-logs
          mountPath: /logs
        - name: volume-podinfo
          mountPath: /etc/podinfo
          readOnly: false
        env:
        - name: POD_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumes:
      - name: volume-logs
        persistentVolumeClaim:
          claimName: logs-hostpath-pvc
      - name: volume-podinfo
        downwardAPI:
          items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
