apiVersion: v1
kind: Service
metadata:
  name: stand-ner-en-ontonotes-lb
  namespace: stand-demo
spec:
  selector:
    app: stand-ner-en-ontonotes-dp
  type: LoadBalancer
  externalIPs:
  - 10.11.1.251
  ports:
  - name: stand-ner-en-ontonotes
    protocol: TCP
    port: 7010
    targetPort: cp6010