apiVersion: v1
kind: Service
metadata:
  name: stand-go-bot-dstc2-lb
  namespace: stand-demo
spec:
  selector:
    app: stand-go-bot-dstc2-dp
  type: LoadBalancer
  externalIPs:
  - 10.11.1.251
  ports:
  - name: stand-go-bot-dstc2
    protocol: TCP
    port: 7566
    targetPort: cp5000