apiVersion: v1
kind: Service
metadata:
  name: demo-sber-faq-lb
  namespace: stand-demo
spec:
  selector:
    app: demo-sber-faq-dp
  type: LoadBalancer
  externalIPs:
  - 10.11.1.251
  ports:
  - name: demo-sber-faq
    protocol: TCP
    port: 7040
    targetPort: cp6040