apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: routerbot-toloka-go-bot-rb-dp
  namespace: stand-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: routerbot-toloka-go-bot-rb-dp
    spec:
      containers:
      - name: routerbot-toloka-go-bot-rb
        image: kubeadm.ipavlov.mipt.ru:5000/stand/router_bot
        ports:
        - name: router-bot-port
          protocol: TCP
          containerPort: 80
        - name: ssh-server-port
          protocol: TCP
          containerPort: 22
        volumeMounts:
        - name: volume-logs
          mountPath: /logs
        - name: volume-rb
          mountPath: /app/router_bot_volume
        - name: volume-podinfo
          mountPath: /etc/podinfo
          readOnly: false
        env:
        - name: POD_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MODEL_NAME
          value: 'routerbot_toloka_go_bot_rb'
        - name: PROXYCHAINS_CONFIG_STRING
          value: 'socks5 159.65.126.171 1337 ipavlov ipavlov_telegram'
        - name: MONGO_PROTOCOL
          value: 'mongodb'
        - name: MONGO_HOST
          value: '127.0.0.1'
        - name: MONGO_PORT
          value: '27017'
        - name: FB_PAGE_ACCESS_TOKEN
          value: 'dummy'
        - name: FB_WEBHOOK
          value: 'https://7066.lnsigo.mipt.ru/fb'
        - name: FB_WEBHOOK_SECRET
          value: 'dummy'
        - name: TG_WEBHOOK
          value: 'https://7066.lnsigo.mipt.ru/tg'
        - name: TG_TOKEN
          value: '768159308:AAFdnmPrdq5od-rc3XyKU3XpFbbXE0ke5AY'
      - name: routerbot-toloka-go-bot-rb-db-mongo
        image: kubeadm.ipavlov.mipt.ru:5000/stand/db/mongo:4.0.6-xenial
        ports:
        - name: mongo-db-port
          protocol: TCP
          containerPort: 27017
        volumeMounts:
        - name: volume-db-data
          mountPath: /db_data
        - name: volume-podinfo-db-mongo
          mountPath: /etc/podinfo
          readOnly: false
        env:
        - name: POD_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: FULL_MODEL_NAME
          value: routerbot_toloka_go_bot_rb_db_mongo
      volumes:
      - name: volume-logs
        persistentVolumeClaim:
          claimName: logs-hostpath-pvc
      - name: volume-rb
        persistentVolumeClaim:
          claimName: rb-hostpath-pvc
      - name: volume-podinfo
        downwardAPI:
          items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
      - name: volume-db-data
        persistentVolumeClaim:
          claimName: db-hostpath-pvc
      - name: volume-podinfo-db-mongo
        downwardAPI:
          items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
            - path: "annotations"
              fieldRef:
                fieldPath: metadata.annotations
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.11.1.254
