apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: stand-ranking-en-dp
  namespace: stand-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stand-ranking-en-dp
    spec:
      containers:
      - name: stand-ranking-en
        image: kubeadm.ipavlov.mipt.ru:5000/stand/ranking_en
        ports:
          - name: cp6009
            protocol: TCP
            containerPort: 6009
        volumeMounts:
        - name: volume-logs
          mountPath: /logs
        - name: volume-podinfo
          mountPath: /etc/podinfo
          readOnly: false
        env:
        - name: POD_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumes:
      - name: volume-logs
        persistentVolumeClaim:
          claimName: logs-hostpath-pvc
      - name: volume-podinfo
        downwardAPI:
          items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
            - path: "annotations"
              fieldRef:
                fieldPath: metadata.annotations