apiVersion: v1
kind: Service
metadata:
  name: {{KUBER_LB_NAME}}
  namespace: stand-demo
spec:
  selector:
    app: {{KUBER_DP_NAME}}
  type: LoadBalancer
  externalIPs:
  - 10.11.1.251
  ports:
  - name: {{FULL_MODEL_NAME_DASHED}}
    protocol: TCP
    port: {{CLUSTER_PORT}}
    targetPort: {{KUBER_CONTAINER_PORT_NAME}}