apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-hostpath-pvc
  namespace: stand-demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: stand-demo-db-hostpath-sc
  resources:
    requests:
      storage: 200Gi