kind: PersistentVolume
apiVersion: v1
metadata:
  name: stand-logs-pv-rbd
  #labels:
  #  type: local
spec:
  #storageClassName: ceph-rbd
  storageClassName: ""
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/share"