apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stand-logs-pvc-hostpath
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: host-path
  resources:
    requests:
      storage: 1Gi