apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-rbd-pvc
  namespace: stand-demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 1Gi