apiVersion: v1
kind: Service
metadata:
  name: stand-ner-ru-lb
  namespace: stand-demo
spec:
  selector:
    app: stand-ner-ru-dp
  type: LoadBalancer
  externalIPs:
  - 10.11.1.251
  ports:
  - name: stand-ner-ru
    protocol: TCP
    port: 7004
    targetPort: cp5000