agent_namespace: '{{AGENT_NAMESPACE}}'

agent:
  name: '{{AGENT_NAME}}'
  response_timeout_sec: {{AGENT_RESPONSE_TIMEOUT}}

  pipeline: {
    utterance_annotators: ['ner'],
    skill_selector: ['chitchat_odqa'],
    skills: ['chitchat', 'odqa'],
    response_selector: ['max_confidence'],
    response_annotators: ['ner'],
    response_formatter: ['test_formatter'],
  }

services:
  {{SERVICE_NAME}}:
    batch_size: {{BATCH_SIZE}}
    infer_timeout_sec: {{SERVICE_INFER_TIMEOUT}}

    connector_params:
      formatter: '{{SERVICE_FORMATTER}}'
      caller: '{{SERVICE_CALLER}}'
      url: '{{SERVICE_URL}}'

channels: {}

database:
  host: localhost
  port: 27017

transport:
  type: '{{TRANSPORT_TYPE}}'

  rabbitmq:
    host: '{{RABBIT_HOST}}'
    port: {{RABBIT_PORT}}
    login: '{{RABBIT_LOGIN}}'
    password: '{{RABBIT_PASSWORD}}'
    virtualhost: '{{RABBIT_VIRTUALHOST}}'
