apiVersion: v1
kind: Service
metadata:
  name: {{KUBER_LB_NAME}}
  namespace: stand-demo
spec:
  selector:
    app: {{KUBER_DP_NAME}}
  type: LoadBalancer
  externalIPs:
  - {{CLUSTER_IP}}
  ports:
  - name: ssh-server
    protocol: TCP
    port: {{CLUSTER_SSH_PORT}}
    targetPort: ssh-server-port