kind: PersistentVolume
apiVersion: v1
metadata:
  name: stand-logs-pv-hostpath
spec:
  storageClassName: host-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/share/stand_demo/logs/"