apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{KUBER_DP_NAME}}
  namespace: stand-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{KUBER_DP_NAME}}
    spec:
      containers:
      - name: {{FULL_MODEL_NAME_DASHED}}
        image: {{KUBER_IMAGE_TAG}}
        ports:
        - name: {{KUBER_CONTAINER_PORT_NAME}}
          protocol: TCP
          containerPort: {{PORT}}
        volumeMounts:
        - name: volume-db-data
          mountPath: /db_data
        - name: volume-podinfo
          mountPath: /etc/podinfo
          readOnly: false
        env:
        - name: POD_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumes:
      - name: volume-db-data
        persistentVolumeClaim:
          claimName: db-hostpath-pvc
      - name: volume-podinfo
        downwardAPI:
          items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - {{DNS_IP}}
