stand:
  - stand_paraphraser_ru
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_squad_ml
  - stand_odqa_ru
  - stand_odqa_en
  - stand_ner_ml
  - stand_sentiment_ru
  - stand_kbqa_ru

http_proxy:
  - http_proxy_vladimir01

demo:
  - demo_transformer_chit_chat_40k_v05_2

dpas_stable:
  - dpas_stable_mongo
  - dpas_stable_skill_odqa
  - dpas_stable_skill_chitchat
  - dpas_stable_annotator_ner
  - dpas_stable_annotator_sentiment
  - dpas_stable_annotator_obscenity
  - dpas_stable_selector_chitchat_odqa

push_pull:
  - stand_paraphraser_ru
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_squad_ml
  - stand_odqa_ru
  - stand_odqa_en
  - stand_ner_ml
  - stand_sentiment_ru
  - stand_kbqa_ru
  - demo_transformer_chit_chat_40k_v05_2

all:
  - stand_paraphraser_ru
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_squad_ml
  - stand_odqa_ru
  - stand_odqa_en
  - stand_ner_ml
  - stand_sentiment_ru
  - stand_kbqa_ru
  - demo_transformer_chit_chat_40k_v05_2
  - http_proxy_vladimir01