stand:
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_odqa_ru
  - stand_odqa_en

http_proxy:
  - http_proxy_litinsky
  - http_proxy_basil

sber:
  - sber_ranking_chitchat_2staged_tfidf_smn_v8
  - sber_ranking_thequest_sub_all_bert

custom: []
demo: []

all:
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_odqa_ru
  - stand_odqa_en
  - sber_ranking_chitchat_2staged_tfidf_smn_v8
  - sber_ranking_thequest_sub_all_bert
