stand:
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_odqa_ru
  - stand_odqa_en

http_proxy:
  - http_proxy_litinsky
  - http_proxy_basil

sber:
  - sber_ranking_chitchat_2staged_tfidf_smn_v8
  - sber_ranking_thequest_sub_all_bert

dpas_test:
# python run.py build -g dpas_test -p create_kuber_no_tests -c ~/dev/stand_models_config.yaml

  - dpas_test_mongo
  - dpas_test_agent
  - dpas_test_skill_odqa
  - dpas_test_skill_chitchat
  - dpas_test_annotator_ner
  - dpas_test_annotator_sentiment
  - dpas_test_annotator_obscenity
  - dpas_test_selector_chitchat_odqa
  - dpas_test_skill_hellobot

dpas_demo:
# python run.py build -g dpas_demo -p create_kuber_no_tests -c ~/dev/stand_models_config.yaml
  - dpas_demo_mongo
  - dpas_demo_agent
  - dpas_demo_skill_chitchat
  - dpas_demo_skill_mailruqa
  - dpas_demo_skill_generalqa
  - dpas_demo_annotator_ner
  - dpas_demo_annotator_sentiment
  - dpas_demo_annotator_obscenity
  - dpas_demo_selector_chitchat_odqa

dpas_demo_cowboys:
  - dpas_demo_cowboy_01
  - dpas_demo_cowboy_02
  - dpas_demo_cowboy_03
  - dpas_demo_cowboy_04
  - dpas_demo_cowboy_05
  #- dpas_demo_cowboy_06

dpas_demo_cowboys_herd:
  # cowboy_01 herd
  - dpas_demo_cowboy_mongo_01
  - dpas_demo_cowboy_skill_chitchat_01
  - dpas_demo_cowboy_skill_mailruqa_01
  - dpas_demo_cowboy_skill_generalqa_01
  - dpas_demo_cowboy_annotator_ner_01
  - dpas_demo_cowboy_annotator_sentiment_01
  - dpas_demo_cowboy_annotator_obscenity_01
  # cowboy_02 herd
  - dpas_demo_cowboy_mongo_02
  - dpas_demo_cowboy_skill_chitchat_02
  - dpas_demo_cowboy_skill_mailruqa_02
  - dpas_demo_cowboy_skill_generalqa_02
  - dpas_demo_cowboy_annotator_ner_02
  - dpas_demo_cowboy_annotator_sentiment_02
  - dpas_demo_cowboy_annotator_obscenity_02
  # cowboy_03 herd
  - dpas_demo_cowboy_mongo_03
  - dpas_demo_cowboy_skill_chitchat_03
  - dpas_demo_cowboy_skill_mailruqa_03
  - dpas_demo_cowboy_skill_generalqa_03
  - dpas_demo_cowboy_annotator_ner_03
  - dpas_demo_cowboy_annotator_sentiment_03
  - dpas_demo_cowboy_annotator_obscenity_03
  # cowboy_04 herd
  - dpas_demo_cowboy_mongo_04
  - dpas_demo_cowboy_skill_chitchat_04
  - dpas_demo_cowboy_skill_mailruqa_04
  - dpas_demo_cowboy_skill_generalqa_04
  - dpas_demo_cowboy_annotator_ner_04
  - dpas_demo_cowboy_annotator_sentiment_04
  - dpas_demo_cowboy_annotator_obscenity_04
  # cowboy_05 herd
  - dpas_demo_cowboy_mongo_05
  - dpas_demo_cowboy_skill_chitchat_05
  - dpas_demo_cowboy_skill_mailruqa_05
  - dpas_demo_cowboy_skill_generalqa_05
  - dpas_demo_cowboy_annotator_ner_05
  - dpas_demo_cowboy_annotator_sentiment_05
  - dpas_demo_cowboy_annotator_obscenity_05
  # cowboy_06 herd
  #- dpas_demo_cowboy_mongo_06
  #- dpas_demo_cowboy_skill_chitchat_06
  #- dpas_demo_cowboy_skill_mailruqa_06
  #- dpas_demo_cowboy_skill_generalqa_06
  #- dpas_demo_cowboy_annotator_ner_06
  #- dpas_demo_cowboy_annotator_sentiment_06
  #- dpas_demo_cowboy_annotator_obscenity_06

custom: []
demo: []

all:
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_odqa_ru
  - stand_odqa_en
  - sber_ranking_chitchat_2staged_tfidf_smn_v8
  - sber_ranking_thequest_sub_all_bert
