stand:
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_odqa_ru
  - stand_odqa_en

demo:
  - demo_ranking_chitchat_2staged_tfidf_smn_v18_g_prep
  - demo_tfidf_autofaq
  - demo_transformer_chit_chat_40k_v01_1_20
  - demo_config_chitchat_vs_odqa

sber:
  - sber_ranking_chitchat_2staged_tfidf_smn_v8
  - sber_ranking_thequest_sub_all_bert

#dpas_test:
#  - dpas_test_mongo

custom: []

all:
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_odqa_ru
  - stand_odqa_en
  - demo_ranking_chitchat_2staged_tfidf_smn_v18_g_prep
  - demo_tfidf_autofaq
  - demo_transformer_chit_chat_40k_v01_1_20
  - demo_config_chitchat_vs_odqa
  - sber_ranking_chitchat_2staged_tfidf_smn_v8

