stand:
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_odqa_ru
  - stand_odqa_en

http_proxy:
  - http_proxy_litinsky
  - http_proxy_basil

custom: []
demo: []

all:
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_odqa_ru
  - stand_odqa_en
