stand:
  - stand_paraphraser_ru
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_squad_ml
  - stand_odqa_ru
  - stand_odqa_en
  - stand_ner_ml
  - stand_sentiment_ru
  - stand_kbqa_ru

http_proxy:
  - http_proxy_jura01
  - http_proxy_cloud_demo_01
  - http_proxy_cloud_demo_02

agent_general:
  - agent_chitchat
  - agent_chitchat_odqa

agent_simple:
  - agent_simple_mongo_db
  - agent_simple_agent
  - agent_simple_service_ner
  - agent_simple_service_chitchat
  - agent_simple_service_odqa
  - agent_simple_service_chitchat_odqa
  - agent_simple_service_max_confidence
  - agent_simple_service_test_formatter

agent_scaled_batch:
  - agent_scaled_batch_mongo_db
  - agent_scaled_batch_agent
  - agent_scaled_batch_service_ner
  - agent_scaled_batch_service_chitchat
  - agent_scaled_batch_service_odqa
  - agent_scaled_batch_service_chitchat_odqa
  - agent_scaled_batch_service_max_confidence
  - agent_scaled_batch_service_test_formatter

agent_scaled_nobatch:
  - agent_scaled_nobatch_mongo_db
  - agent_scaled_nobatch_agent
  - agent_scaled_nobatch_service_ner
  - agent_scaled_nobatch_service_chitchat
  - agent_scaled_nobatch_service_odqa
  - agent_scaled_nobatch_service_chitchat_odqa
  - agent_scaled_nobatch_service_max_confidence
  - agent_scaled_nobatch_service_test_formatter

push_pull:
  - stand_paraphraser_ru
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_squad_ml
  - stand_odqa_ru
  - stand_odqa_en
  - stand_ner_ml
  - stand_sentiment_ru
  - stand_kbqa_ru

all:
  - stand_paraphraser_ru
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_squad_ml
  - stand_odqa_ru
  - stand_odqa_en
  - stand_ner_ml
  - stand_sentiment_ru
  - stand_kbqa_ru
  - http_proxy_jura01
  - http_proxy_cloud_demo_01
  - http_proxy_cloud_demo_02
  - agent_chitchat
  - agent_chitchat_odqa