stand:
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_odqa_ru
  - stand_odqa_en

http_proxy:
  - http_proxy_litinsky
  - http_proxy_basil

custom: []

demo:
  - demo_transformer_chit_chat_40k_v05
  - demo_transformer_chit_chat_40k_v05_2
  - demo_bert_ranker_bot_3
  - demo_ru_odqa_infer_wiki_rubert_noans
  - demo_ru_odqa_infer_wiki_rubert_noans_rest

all:
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_odqa_ru
  - stand_odqa_en
