stand:
  - stand_paraphraser_ru
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_squad_ml
  - stand_odqa_ru
  - stand_odqa_en
  - stand_ner_ml
  - stand_sentiment_ru
  - stand_kbqa_ru

http_proxy:
  - http_proxy_jura01
  - http_proxy_cloud_demo_01
  - http_proxy_cloud_demo_02

agent_obsolete_services:
  - agent_chitchat
  - agent_chitchat_odqa

push_pull:
  - stand_paraphraser_ru
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_squad_ml
  - stand_odqa_ru
  - stand_odqa_en
  - stand_ner_ml
  - stand_sentiment_ru
  - stand_kbqa_ru

all:
  - stand_paraphraser_ru
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_squad_ml
  - stand_odqa_ru
  - stand_odqa_en
  - stand_ner_ml
  - stand_sentiment_ru
  - stand_kbqa_ru
  - http_proxy_jura01
  - http_proxy_cloud_demo_01
  - http_proxy_cloud_demo_02