stand:
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_odqa_ru
  - stand_odqa_en
  - stand_ner_ml

http_proxy:
  - http_proxy_litinsky
  - http_proxy_basil

custom: []

dpas_stable:
  - dpas_stable_mongo
  - dpas_stable_skill_odqa
  - dpas_stable_skill_chitchat
  - dpas_stable_annotator_ner
  - dpas_stable_annotator_sentiment
  - dpas_stable_annotator_obscenity
  - dpas_stable_selector_chitchat_odqa

all:
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_odqa_ru
  - stand_odqa_en
