stand:
  - stand_paraphraser_ru
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_squad_cn
  - stand_squad_ml
  - stand_odqa_ru
  - stand_odqa_en
  - stand_ner_ml
  - stand_sentiment_ru
  - stand_kbqa_ru

http_proxy:
  - http_proxy_cloud_demo_01
  - http_proxy_cloud_demo_02

alexaprize_idris_repo:
  - alexaprize_idris_repo_rb
  - alexaprize_idris_repo_rbp
  - alexaprize_idris_repo_rb_dev
  - alexaprize_idris_repo_rbp_dev

agent_nti_gopnik:
  - agent_nti_gopnik
  - agent_nti_gopnik_mongo_db
  - agent_nti_gopnik_odqa
  - agent_nti_gopnik_ranking_chitchat_2stage
  - agent_nti_gopnik_ner
  - agent_nti_gopnik_sentiment
  - agent_nti_gopnik_rb
  - agent_nti_gopnik_rbp

push_pull:
  - stand_paraphraser_ru
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_squad_cn
  - stand_squad_ml
  - stand_odqa_ru
  - stand_odqa_en
  - stand_ner_ml
  - stand_sentiment_ru
  - stand_kbqa_ru

all:
  - stand_paraphraser_ru
  - stand_ner_ru
  - stand_ner_en
  - stand_intents_en
  - stand_insults_en
  - stand_ranking_en
  - stand_squad_ru
  - stand_squad_en
  - stand_squad_cn
  - stand_squad_ml
  - stand_odqa_ru
  - stand_odqa_en
  - stand_ner_ml
  - stand_sentiment_ru
  - stand_kbqa_ru
  - http_proxy_cloud_demo_01
  - http_proxy_cloud_demo_02
  - alexaprize_idris_repo_rb
  - alexaprize_idris_repo_rbp