apiVersion: v1
kind: Service
metadata:
  name: stand-ner-ml-lb
  namespace: stand-demo
spec:
  selector:
    app: stand-ner-ml-dp
  type: LoadBalancer
  externalIPs:
  - 10.11.1.251
  ports:
  - name: stand-ner-ml
    protocol: TCP
    port: 7013
    targetPort: cp5000