kind: PersistentVolume
apiVersion: v1
metadata:
  name: stand-demo-components-hostpath-pv
  namespace: stand-demo
spec:
  storageClassName: stand-demo-components-hostpath-sc
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/share/stand_demo/dp_components/"