apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: stand-squad-ru-dp
  namespace: stand-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stand-squad-ru-dp
    spec:
      containers:
      - name: stand-squad-ru
        image: kubeadm.ipavlov.mipt.ru:5000/stand/squad_ru
        resources:
          limits:
            nvidia.com/gpu: 1
        ports:
          - name: cp6005
            protocol: TCP
            containerPort: 6005
        volumeMounts:
        - name: volume-logs
          mountPath: /vol
      volumes:
      - name: volume-logs
        #emptyDir: {}
        persistentVolumeClaim:
          #claimName: stand-logs-pvc-rbd
          claimName: logs-hostpath-pvc