apiVersion: v1
kind: Service
metadata:
  name: stand-squad-ru-lb
spec:
  selector:
    app: stand-squad-ru-dp
  type: LoadBalancer
  externalIPs:
  - 10.11.1.251
  ports:
  - name: stand-squad-ru
    protocol: TCP
    port: 6005
    targetPort: cp6005