apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: stand-monitoring-dp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stand-monitoring-dp
    spec:
      serviceAccountName: prometheus
      containers:
      - name: stand-monitoring
        image: kubeadm.ipavlov.mipt.ru:5000/stand/monitoring
        ports:
        - name: cp9090
          protocol: TCP
          containerPort: 9090
        volumeMounts:
        - name: volume-logs
          mountPath: /logs
        - name: volume-podinfo
          mountPath: /etc/podinfo
          readOnly: false
        env:
        - name: POD_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumes:
      - name: volume-logs
        persistentVolumeClaim:
          claimName: logs-monitoring-hostpath-pvc
      - name: volume-podinfo
        downwardAPI:
          items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations