apiVersion: v1
kind: Service
metadata:
  name: stand-monitoring-lb
spec:
  selector:
    app: stand-monitoring-dp
  type: LoadBalancer
  externalIPs:
  - 10.11.1.251
  ports:
  - name: stand-monitoring-prometheus
    protocol: TCP
    port: 9090
    targetPort: cp9090
  - name: stand-monitoring-grafana
    protocol: TCP
    port: 9091
    targetPort: cp3000