apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: stand-http-proxy-basil-dp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stand-http-proxy-basil-dp
    spec:
      containers:
      - name: stand-http-proxy-basil
        image: kubeadm.ipavlov.mipt.ru:5000/stand/http_proxy
        ports:
        - name: cp7054
          protocol: TCP
          containerPort: 7054
        env:
        - name: LISTENED_PORT
          value: "7054"
        - name: PROXYED_HOST
          value: "192.168.20.110"
        - name: PROXYED_PORT
          value: "7054"