# Agent infrastructure
agent_scaled_batch_mongo_db:
  TEMPLATE: mongo_db
  CLUSTER_PORT: 10011

# Agent
agent_scaled_batch_agent:
  TEMPLATE: agent_agent
  AGENT_NAMESPACE: "deeppavlov_agent_scaled_batch"
  AGENT_NAME: "dp_agent_scaled_batch"
  MONGO_PORT: 10011

# Services
agent_scaled_batch_service_ner:
  TEMPLATE: agent_service_http
  AGENT_NAMESPACE: "deeppavlov_agent_scaled_batch"
  AGENT_NAME: "dp_agent_scaled_batch"
  REPLICAS_NUM: 3
  BATCH_SIZE: 20
  SERVICE_IMAGE_TAG: kubeadm.ipavlov.mipt.ru:5000/stand/ner_ru
  CONFIG: ner_rus_bert
  SERVICE_NAME: ner
  SERVICE_FORMATTER: "deeppavlov_ner_stand"

agent_scaled_batch_service_chitchat:
  TEMPLATE: agent_service_http
  AGENT_NAMESPACE: "deeppavlov_agent_scaled_batch"
  AGENT_NAME: "dp_agent_scaled_batch"
  REPLICAS_NUM: 9
  BATCH_SIZE: 20
  SERVICE_IMAGE_TAG: kubeadm.ipavlov.mipt.ru:5000/agent_obsolete
  CONFIG: legacy_components/skills/ranking_chitchat/agent_ranking_chitchat_2staged_tfidf_smn_v4_prep.json
  SERVICE_NAME: chitchat
  SERVICE_FORMATTER: "agent_ranking_chitchat_prep" 

agent_scaled_batch_service_odqa:
  TEMPLATE: agent_service_http
  AGENT_NAMESPACE: "deeppavlov_agent_scaled_batch"
  AGENT_NAME: "dp_agent_scaled_batch"
  REPLICAS_NUM: 9
  GPU_UNITS_NUM: 1
  BATCH_SIZE: 20
  SERVICE_IMAGE_TAG: kubeadm.ipavlov.mipt.ru:5000/stand/odqa_ru
  CONFIG: ru_odqa_infer_wiki_rubert_noans
  SERVICE_NAME: odqa
  SERVICE_FORMATTER: "deeppavlov_odqa_stand" 

agent_scaled_batch_service_chitchat_odqa:
  TEMPLATE: agent_service_http
  AGENT_NAMESPACE: "deeppavlov_agent_scaled_batch"
  AGENT_NAME: "dp_agent_scaled_batch"
  REPLICAS_NUM: 9
  BATCH_SIZE: 20
  SERVICE_IMAGE_TAG: kubeadm.ipavlov.mipt.ru:5000/agent_obsolete
  CONFIG: legacy_components/skill_selectors/chitchat_odqa_selector/sselector_chitchat_odqa.json
  SERVICE_NAME: chitchat_odqa
  SERVICE_FORMATTER: "agent_chitchat_odqa_selector"

agent_scaled_batch_service_max_confidence:
  TEMPLATE: agent_service_python
  AGENT_NAMESPACE: "deeppavlov_agent_scaled_batch"
  AGENT_NAME: "dp_agent_scaled_batch"
  REPLICAS_NUM: 3
  BATCH_SIZE: 20
  SERVICE_NAME: max_confidence
  SERVICE_FORMATTER: "agent_max_conf_response_selector"

agent_scaled_batch_service_test_formatter:
  TEMPLATE: agent_service_python
  AGENT_NAMESPACE: "deeppavlov_agent_scaled_batch"
  AGENT_NAME: "dp_agent_scaled_batch"
  REPLICAS_NUM: 3
  BATCH_SIZE: 20
  SERVICE_NAME: test_formatter
  SERVICE_FORMATTER: "agent_test_response_formatter"
