dev_mongo_rb:
  TEMPLATE: mongo_db
  CLUSTER_PORT: 10001
  pipeline: all_up_kuber_no_tests

dev_http_proxy_rb:
  TEMPLATE: http_proxy
  CLUSTER_PORT: 7051
  PROXYED_HOST: 192.168.10.221
  PROXYED_PORT: 8080