# AGENT
dpas_stable_agent:
  BRANCH: agent-stable
  TEMPLATE: dpas_agent
  pipeline: all_up_kuber_no_tests

  agent_config:
    db_config:
      DB_NAME: test
      HOST: 10.11.1.251
      PORT: 8100

    agent_config:
      MAX_WORKERS: 4

      SKILLS:
        - name: odqa
          url: http://10.11.1.251:8101/skill
          path: null
          #configs/dp_assistant/agent_ru_odqa_retr_noans_rubert_infer.json

        - name: chitchat
          url: http://10.11.1.251:8102/skill
          path: null
          #configs/dp_assistant/agent_ranking_chitchat_2staged_tfidf_smn_v4.json
          env:
            CUDA_VISIBLE_DEVICES: ""

        #- name: hellobot
        #  url: http://10.11.1.251:8106/ruler_call/
        #  path: null

        #- name: sberchat
        #  url: http://23.102.48.212:8443/api/
        #  path: null

      ANNOTATORS:
        - name: ner
          url: http://10.11.1.251:8103/skill
          path: null
          #configs/dp_assistant/preproc_ner_rus.json
          env:
            CUDA_VISIBLE_DEVICES: ""

        - name: sentiment
          url: http://10.11.1.251:8104/skill
          path: null
          #configs/dp_assistant/preproc_rusentiment.json
          env:
            CUDA_VISIBLE_DEVICES: ""

        - name: obscenity
          url: http://10.11.1.251:8107/skill
          path: null
          #configs/dp_assistant/obscenity_classifier.json
          env:
            CUDA_VISIBLE_DEVICES: ""

      SKILL_SELECTORS:
        - name: chitchat_odqa
          url: http://10.11.1.251:8105/skill
          path: null
          #configs/dp_assistant/sselector_chitchat_odqa.json
          env:
            CUDA_VISIBLE_DEVICES: ""

      RESPONSE_SELECTORS: []

# DATABASE
dpas_stable_mongo:
  TEMPLATE: mongo_db
  CLUSTER_PORT: 8100
  pipeline: all_up_kuber_no_tests

# SKILLS
dpas_stable_skill_odqa:
  CONFIG_FILE: dp_assistant/agent_ru_odqa_retr_noans_rubert_infer.json
  BRANCH: agent-stable
  TEMPLATE: dp_obsolete_gpu
  PORT: 80
  CLUSTER_PORT: 8101
  run_params:
    --api-mode: "skill"
  pipeline: all_up_kuber_no_tests

dpas_stable_skill_chitchat:
  CONFIG_FILE: dp_assistant/agent_ranking_chitchat_2staged_tfidf_smn_v4.json
  BRANCH: agent-stable
  TEMPLATE: dp_obsolete_gpu
  PORT: 80
  CLUSTER_PORT: 8102
  run_params:
    --api-mode: "skill"
  pipeline: all_up_kuber_no_tests

dpas_stable_skill_hellobot:
  TEMPLATE: dpas_custom_hellobot
  CLUSTER_PORT: 8106
  pipeline: all_up_kuber_no_tests

# ANNOTATORS
dpas_stable_annotator_ner:
  CONFIG_FILE: dp_assistant/preproc_ner_rus.json
  BRANCH: agent-stable
  TEMPLATE: dp_obsolete_no_gpu
  PORT: 80
  CLUSTER_PORT: 8103
  run_params:
    --api-mode: "skill"
  pipeline: all_up_kuber_no_tests

dpas_stable_annotator_sentiment:
  CONFIG_FILE: dp_assistant/preproc_rusentiment.json
  BRANCH: agent-stable
  TEMPLATE: dp_obsolete_no_gpu
  PORT: 80
  CLUSTER_PORT: 8104
  run_params:
    --api-mode: "skill"
  pipeline: all_up_kuber_no_tests

dpas_stable_annotator_obscenity:
  CONFIG_FILE: dp_assistant/obscenity_classifier.json
  BRANCH: agent-stable
  TEMPLATE: dp_obsolete_no_gpu
  PORT: 80
  CLUSTER_PORT: 8107
  run_params:
    --api-mode: "skill"
  pipeline: all_up_kuber_no_tests

# SKILL_SELECTORS
dpas_stable_selector_chitchat_odqa:
  CONFIG_FILE: dp_assistant/sselector_chitchat_odqa.json
  BRANCH: agent-stable
  TEMPLATE: dp_obsolete_no_gpu
  PORT: 80
  CLUSTER_PORT: 8105
  run_params:
    --api-mode: "skill"
  pipeline: all_up_kuber_no_tests