dpas_ru_odqa_infer_wiki:
  MODEL_NAME: ru_odqa_infer_wiki
  PREFIX: dpas
  CONFIG_FILE: odqa/ru_odqa_infer_wiki.json
  TEMPLATE: rb_no_gpu_custom
  BRANCH: dev
  CUDA_VERSION: 9.0
  PORT: 6064
  CLUSTER_PORT: 7064
  DOCKER_REGISTRY: kubeadm.ipavlov.mipt.ru:5000
  run_mode: ""
  run_params:
    _flags: ["--default-skill"]
    --host: 10.11.1.58
    --port: 8433
    --token: cd496eee-61a5-4d0a-a0a0-d5090d750d57
  pipeline: all_up_kuber_no_tests

dpas_ranking_mailru_bert:
  MODEL_NAME: ranking_mailru_bert
  PREFIX: dpas
  CONFIG_FILE: ranking/ranking_mailru_bert.json
  TEMPLATE: rb_gpu_custom
  BRANCH: feat/bert_ranker_bot
  CUDA_VERSION: 9.0
  PORT: 6061
  CLUSTER_PORT: 7061
  DOCKER_REGISTRY: kubeadm.ipavlov.mipt.ru:5000
  run_mode: ""
  run_params:
    _flags: ["--default-skill"]
    --host: 10.11.1.58
    --port: 8433
    --token: 343f5688-4df9-4ef1-a05e-cfd9af9114aa
  pipeline: all_up_kuber_no_tests

dpas_ranking_chitchat_2staged_tfidf_smn_v4:
  MODEL_NAME: ranking_chitchat_2staged_tfidf_smn_v4
  PREFIX: dpas
  CONFIG_FILE: ranking/ranking_chitchat_2staged_tfidf_smn_v4.json
  TEMPLATE: rb_gpu_custom
  BRANCH: hybrid_ranker
  CUDA_VERSION: 9.0
  PORT: 6062
  CLUSTER_PORT: 7062
  DOCKER_REGISTRY: kubeadm.ipavlov.mipt.ru:5000
  run_mode: ""
  run_params:
    _flags: []
    --host: 10.11.1.58
    --port: 8433
    --token: 7efabf80-8298-4cd4-99c2-aa93c3c2a8f9
  pipeline: all_up_kuber_no_tests


dpas_ranking_chitchat_2staged_tfidf_smn_v11:
  MODEL_NAME: ranking_chitchat_2staged_tfidf_smn_v11
  PREFIX: dpas
  CONFIG_FILE: ranking/ranking_chitchat_2staged_tfidf_smn_v11.json
  TEMPLATE: rb_gpu_custom
  BRANCH: hybrid_ranker
  CUDA_VERSION: 9.0
  PORT: 6063
  CLUSTER_PORT: 7063
  DOCKER_REGISTRY: kubeadm.ipavlov.mipt.ru:5000
  run_mode: ""
  run_params:
    _flags: []
    --host: 10.11.1.58
    --port: 8433
    --token: b5e47087-cdc6-42cb-a04f-179f3afa4b0e
  pipeline: all_up_kuber_no_tests

dpas_mailru:
  MODEL_NAME: mailru
  PREFIX: dpas
  CONFIG_FILE: odqa/mailru.json
  TEMPLATE: rb_no_gpu_custom
  BRANCH: question_bots
  CUDA_VERSION: 9.0
  PORT: 6067
  CLUSTER_PORT: 7067
  DOCKER_REGISTRY: kubeadm.ipavlov.mipt.ru:5000
  run_mode: ""
  run_params:
    _flags: ["--default-skill"]
    --host: 10.11.1.58
    --port: 8433
    --token: 6872a219-e75c-4a19-9ad1-178948ce4d00
  pipeline: all_up_kuber_no_tests

dpas_thequestion:
  MODEL_NAME: thequestion
  PREFIX: dpas
  CONFIG_FILE: odqa/thequestion.json
  TEMPLATE: rb_no_gpu_custom
  BRANCH: question_bots
  CUDA_VERSION: 9.0
  PORT: 6068
  CLUSTER_PORT: 7068
  DOCKER_REGISTRY: kubeadm.ipavlov.mipt.ru:5000
  run_mode: ""
  run_params:
    _flags: ["--default-skill"]
    --host: 10.11.1.58
    --port: 8433
    --token: e3bd62fa-ee63-4001-b409-f9fe535df690
  pipeline: all_up_kuber_no_tests

dpas_ranking_mailru_bert_1:
  MODEL_NAME: ranking_mailru_bert_1
  PREFIX: dpas
  CONFIG_FILE: ranking/ranking_mailru_bert_1.json
  TEMPLATE: rb_gpu_custom
  BRANCH: feat/bert_ranker_bot_3
  CUDA_VERSION: 9.0
  PORT: 6070
  CLUSTER_PORT: 7070
  DOCKER_REGISTRY: kubeadm.ipavlov.mipt.ru:5000
  run_mode: ""
  run_params:
    _flags: ["--default-skill"]
    --host: 10.11.1.58
    --port: 8433
    --token: e3778877-5f22-4ff8-9011-62065d4491e6
  pipeline: all_up_kuber_no_tests

dpas_ranking_mailru_bert_2:
  MODEL_NAME: ranking_mailru_bert_2
  PREFIX: dpas
  CONFIG_FILE: ranking/ranking_mailru_bert_2.json
  TEMPLATE: rb_gpu_custom
  BRANCH: feat/bert_ranker_bot_3
  CUDA_VERSION: 9.0
  PORT: 6071
  CLUSTER_PORT: 7071
  DOCKER_REGISTRY: kubeadm.ipavlov.mipt.ru:5000
  run_mode: ""
  run_params:
    _flags: ["--default-skill"]
    --host: 10.11.1.58
    --port: 8433
    --token: 6efbb8eb-339b-4870-8d3e-01bee901b2af
  pipeline: all_up_kuber_no_tests

dpas_ranking_mailru_bert_3:
  MODEL_NAME: ranking_mailru_bert_3
  PREFIX: dpas
  CONFIG_FILE: ranking/ranking_mailru_bert_3.json
  TEMPLATE: rb_gpu_custom
  BRANCH: feat/bert_ranker_bot_3
  CUDA_VERSION: 9.0
  PORT: 6072
  CLUSTER_PORT: 7072
  DOCKER_REGISTRY: kubeadm.ipavlov.mipt.ru:5000
  run_mode: ""
  run_params:
    _flags: ["--default-skill"]
    --host: 10.11.1.58
    --port: 8433
    --token: bc3684dd-0d3c-4c83-b4c9-7c0d9464c48d
  pipeline: all_up_kuber_no_tests

dpas_ranking_mailru_bert_4:
  MODEL_NAME: ranking_mailru_bert_4
  PREFIX: dpas
  CONFIG_FILE: ranking/ranking_mailru_bert_4.json
  TEMPLATE: rb_gpu_custom
  BRANCH: feat/bert_ranker_bot_3
  CUDA_VERSION: 9.0
  PORT: 6073
  CLUSTER_PORT: 7073
  DOCKER_REGISTRY: kubeadm.ipavlov.mipt.ru:5000
  run_mode: ""
  run_params:
    _flags: ["--default-skill"]
    --host: 10.11.1.58
    --port: 8433
    --token: dca8f018-00d1-4a90-ab5a-b69318db622c
  pipeline: all_up_kuber_no_tests