sber_ranking_chitchat_2staged_tfidf_smn_v8:
  CONFIG_FILE: ranking/ranking_chitchat_2staged_tfidf_smn_v8.json
  TEMPLATE: dp_gpu
  BRANCH: hybrid_ranker
  CLUSTER_PORT: 7069
  MODEL_ARGS: ["utterance", "history", "dummy_state"]
  pipeline: all_up_kuber_no_tests

sber_ranking_thequest_sub_all_bert:
  CONFIG_FILE: ranking/ranking_thequest_sub_all_bert.json
  TEMPLATE: dp_gpu
  BRANCH: feat/bert_ranker_bot_2_thequest_sub_all
  CLUSTER_PORT: 7062
  MODEL_ARGS: ["text1"]
  pipeline: all_up_kuber