dev_mongo_db:
  TEMPLATE: mongo_db
  CLUSTER_PORT: 10001

dev_agent_odqa_ru:
  CONFIG: ru_odqa_infer_wiki_rubert_noans
  TEMPLATE: dp
  BASE_IMAGE: "deeppavlov/base-gpu:0.6.1"
  GPU_UNITS_NUM: 1
  CLUSTER_PORT: 7030
  image_polling_timeout_sec: 600
  deployment_polling_timeout_sec: 1200
  pipeline: all_up_kuber
