dev_mongo_db:
  TEMPLATE: mongo_db
  CLUSTER_PORT: 10001

demo_transformer_chitchat_pasha:
  CONFIG: "transformer_chit_chat_40k_v05"
  TEMPLATE: dp
  COMMIT: "72bf7715a7a8df80fed82203ad5d482809bdf0c8"
  BASE_IMAGE: "deeppavlov/base-gpu:0.6.1"
  CLUSTER_PORT: 6001
  MODEL_ARGS: ["text1"]
  image_polling_timeout_sec: 1200
  deployment_polling_timeout_sec: 2400
  pipeline: all_up_kuber
