sber_ranking_chitchat_2staged_tfidf_smn_v8:
  CONFIG_FILE: ranking/ranking_chitchat_2staged_tfidf_smn_v8.json
  TEMPLATE: dp_gpu
  BRANCH: hybrid_ranker
  CLUSTER_PORT: 7069
  MODEL_ARGS: ["utterance", "history", "dummy_state"]
  pipeline: all_up_kuber_no_tests

sber_ranking_thequest_sub_all_bert:
  CONFIG_FILE: ranking/ranking_thequest_sub_all_bert.json
  TEMPLATE: dp_gpu
  BRANCH: feat/bert_ranker_bot_2_thequest_sub_all
  CLUSTER_PORT: 7062
  MODEL_ARGS: ["text1"]
  pipeline: all_up_kuber

demo_transformer_chit_chat_40k_v05:
  CONFIG_FILE: generative_chit_chat/transformer_chit_chat_40k_v05.json
  TEMPLATE: dp_obsolete_gpu
  BRANCH: f727668
  CLUSTER_PORT: 7061
  run_mode: "interactmsbot"
  run_flags: ["--no-default-skill", "--stateful"]
  pipeline: all_up_kuber_no_tests

demo_bert_ranker_bot_3:
  CONFIG_FILE: ranking/ranking_mailru_bert_1.json
  TEMPLATE: dp_obsolete_gpu
  BRANCH: bot/bert_ranker_bot_3
  CLUSTER_PORT: 7062
  run_mode: "interactmsbot"
  run_flags: ["--stateful"]
  pipeline: all_up_kuber_no_tests
