routerbot_toloka_dialog_rus_bot:
  TEMPLATE: router_bot
  CLUSTER_PORT: 7062
  CLUSTER_MONGO_PORT: 10062
  CLUSTER_SSH_PORT: 8062
  FB_PAGE_ACCESS_TOKEN: "dummy"
  FB_WEBHOOK_SECRET: "dummy"

alexaprize_idris_repo_rb:
  TEMPLATE: router_bot
  CLUSTER_PORT: 7063
  CLUSTER_MONGO_PORT: 10063
  CLUSTER_SSH_PORT: 8063
  FB_PAGE_ACCESS_TOKEN: "dummy"
  FB_WEBHOOK_SECRET: "dummy"

alexaprize_idris_repo_rbp:
  TEMPLATE: router_bot_poller
  run_flags: ["--agent"]

alexaprize_idris_repo_rb_dev:
  TEMPLATE: router_bot
  CLUSTER_PORT: 7064
  CLUSTER_MONGO_PORT: 10064
  CLUSTER_SSH_PORT: 8064
  FB_PAGE_ACCESS_TOKEN: "dummy"
  FB_WEBHOOK_SECRET: "dummy"

alexaprize_idris_repo_rbp_dev:
  TEMPLATE: router_bot_poller
  run_flags: ["--agent"]

agent_nti_gopnik_rb:
  TEMPLATE: router_bot
  CLUSTER_PORT: 7067
  CLUSTER_MONGO_PORT: 10067
  CLUSTER_SSH_PORT: 8067
  FB_PAGE_ACCESS_TOKEN: "dummy"
  FB_WEBHOOK_SECRET: "dummy"

agent_nti_gopnik_rbp:
  TEMPLATE: router_bot_poller
  run_flags: ["--agent"]
  run_params:
    --model_url: "http://10.11.1.251:7059/"
    --host: "10.11.1.251"
    --port: "7067"
    --token: "agent_nti_gopnik"