stand_ner_ru:
  CONFIG_FILE: ner/ner_rus.json
  TEMPLATE: dp_no_gpu
  CLUSTER_PORT: 7004
  MODEL_ARGS: ["text1"]
  image_polling_timeout_sec: 300
  deployment_polling_timeout_sec: 600
  pipeline: all_up_kuber

stand_ner_en:
  CONFIG_FILE: ner/ner_ontonotes.json
  TEMPLATE: dp_no_gpu
  CLUSTER_PORT: 7010
  MODEL_ARGS: ["text1"]
  image_polling_timeout_sec: 300
  deployment_polling_timeout_sec: 600
  pipeline: all_up_kuber

stand_squad_ru:
  CONFIG_FILE: squad/squad_ru.json
  TEMPLATE: dp_no_gpu
  CLUSTER_PORT: 7005
  MODEL_ARGS: ["text1", "text2"]
  image_polling_timeout_sec: 300
  deployment_polling_timeout_sec: 600
  pipeline: all_up_kuber

stand_squad_en:
  CONFIG_FILE: squad/squad.json
  TEMPLATE: dp_no_gpu
  CLUSTER_PORT: 7008
  MODEL_ARGS: ["text1", "text2"]
  image_polling_timeout_sec: 300
  deployment_polling_timeout_sec: 600
  pipeline: all_up_kuber

stand_intents_en:
  CONFIG_FILE: classifiers/intents_snips.json
  TEMPLATE: dp_no_gpu
  CLUSTER_PORT: 7007
  MODEL_ARGS: ["text1"]
  image_polling_timeout_sec: 300
  deployment_polling_timeout_sec: 600
  pipeline: all_up_kuber

stand_ranking_en:
  CONFIG_FILE: ranking/ranking_insurance_interact.json
  TEMPLATE: dp_no_gpu
  CLUSTER_PORT: 7009
  MODEL_ARGS: ["text1"]
  image_polling_timeout_sec: 600
  deployment_polling_timeout_sec: 2400
  pipeline: all_up_kuber

stand_insults_en:
  CONFIG_FILE: classifiers/insults_kaggle.json
  TEMPLATE: dp_no_gpu
  CLUSTER_PORT: 7006
  MODEL_ARGS: ["text1"]
  image_polling_timeout_sec: 600
  deployment_polling_timeout_sec: 2400
  pipeline: all_up_kuber

stand_odqa_en:
  CONFIG_FILE: odqa/en_odqa_pop_infer_enwiki20180211.json
  TEMPLATE: dp_gpu
  CLUSTER_PORT: 7011
  MODEL_ARGS: ["text1"]
  image_polling_timeout_sec: 1200
  deployment_polling_timeout_sec: 2400
  pipeline: all_up_kuber

stand_odqa_ru:
  CONFIG_FILE: odqa/ru_odqa_infer_wiki_rubert_noans.json
  TEMPLATE: dp_gpu
  BRANCH: feat/bert
  CLUSTER_PORT: 7012
  MODEL_ARGS: ["text1"]
  image_polling_timeout_sec: 600
  deployment_polling_timeout_sec: 1200
  pipeline: all_up_kuber
