stand_ner_ru:
  MODEL_NAME: ner_ru
  PREFIX: stand
  CONFIG_FILE: ner/ner_rus.json
  TEMPLATE: no_gpu
  CUDA_VERSION: 9.0
  PORT: 6004
  CLUSTER_PORT: 7004
  MODEL_ARGS: ["text1"]
  DOCKER_REGISTRY: kubeadm.ipavlov.mipt.ru:5000
  run_mode: riseapi
  image_polling_timeout_sec: 120
  deployment_polling_timeout_sec: 600
  pipeline: all_up_kuber

stand_ner_en:
  MODEL_NAME: ner_en
  PREFIX: stand
  CONFIG_FILE: ner/ner_ontonotes.json
  TEMPLATE: no_gpu
  CUDA_VERSION: 9.0
  PORT: 6010
  CLUSTER_PORT: 7010
  MODEL_ARGS: ["text1"]
  DOCKER_REGISTRY: kubeadm.ipavlov.mipt.ru:5000
  run_mode: riseapi
  image_polling_timeout_sec: 120
  deployment_polling_timeout_sec: 600
  pipeline: all_up_kuber

stand_sqad_ru:
  MODEL_NAME: squad_ru
  PREFIX: stand
  CONFIG_FILE: squad/squad_ru.json
  TEMPLATE: no_gpu
  CUDA_VERSION: 9.0
  PORT: 6005
  CLUSTER_PORT: 7005
  MODEL_ARGS: ["text1", "text2"]
  DOCKER_REGISTRY: kubeadm.ipavlov.mipt.ru:5000
  run_mode: riseapi
  image_polling_timeout_sec: 120
  deployment_polling_timeout_sec: 600
  pipeline: all_up_kuber

stand_squad_en:
  MODEL_NAME: squad_en
  PREFIX: stand
  CONFIG_FILE: squad/squad.json
  TEMPLATE: no_gpu
  CUDA_VERSION: 9.0
  PORT: 6008
  CLUSTER_PORT: 7008
  MODEL_ARGS: ["text1", "text2"]
  DOCKER_REGISTRY: kubeadm.ipavlov.mipt.ru:5000
  run_mode: riseapi
  image_polling_timeout_sec: 120
  deployment_polling_timeout_sec: 600
  pipeline: all_up_kuber

stand_intents_en:
  MODEL_NAME: intents_en
  PREFIX: stand
  CONFIG_FILE: classifiers/intents_snips.json
  TEMPLATE: no_gpu
  CUDA_VERSION: 9.0
  PORT: 6007
  CLUSTER_PORT: 7007
  MODEL_ARGS: ["text1"]
  DOCKER_REGISTRY: kubeadm.ipavlov.mipt.ru:5000
  run_mode: riseapi
  image_polling_timeout_sec: 120
  deployment_polling_timeout_sec: 600
  pipeline: all_up_kuber

stand_ranking_en:
  MODEL_NAME: ranking_en
  PREFIX: stand
  CONFIG_FILE: ranking/ranking_insurance_interact.json
  TEMPLATE: no_gpu
  CUDA_VERSION: 9.0
  PORT: 6009
  CLUSTER_PORT: 7009
  MODEL_ARGS: ["text1"]
  DOCKER_REGISTRY: kubeadm.ipavlov.mipt.ru:5000
  run_mode: riseapi
  image_polling_timeout_sec: 600
  deployment_polling_timeout_sec: 1200
  pipeline: all_up_kuber

stand_insults_en:
  MODEL_NAME: insults_en
  PREFIX: stand
  CONFIG_FILE: classifiers/insults_kaggle.json
  TEMPLATE: no_gpu
  CUDA_VERSION: 9.0
  PORT: 6006
  CLUSTER_PORT: 7006
  MODEL_ARGS: ["text1"]
  DOCKER_REGISTRY: kubeadm.ipavlov.mipt.ru:5000
  run_mode: riseapi
  image_polling_timeout_sec: 120
  deployment_polling_timeout_sec: 1200
  pipeline: all_up_kuber

stand_odqa_en:
  MODEL_NAME: odqa_en
  PREFIX: stand
  CONFIG_FILE: odqa/en_odqa_pop_infer_enwiki20180211.json
  TEMPLATE: gpu
  CUDA_VERSION: 9.0
  PORT: 6011
  CLUSTER_PORT: 7011
  MODEL_ARGS: ["text1"]
  DOCKER_REGISTRY: kubeadm.ipavlov.mipt.ru:5000
  run_mode: riseapi
  image_polling_timeout_sec: 1200
  deployment_polling_timeout_sec: 2400
  pipeline: all_up_kuber

stand_odqa_ru:
  MODEL_NAME: odqa_ru
  PREFIX: stand
  CONFIG_FILE: odqa/ru_odqa_infer_wiki_retr_noans.json
  TEMPLATE: gpu_custom
  BRANCH: squad_with_retr_data
  CUDA_VERSION: 9.0
  PORT: 6012
  CLUSTER_PORT: 7012
  MODEL_ARGS: ["text1"]
  DOCKER_REGISTRY: kubeadm.ipavlov.mipt.ru:5000
  run_mode: riseapi
  image_polling_timeout_sec: 600
  deployment_polling_timeout_sec: 1200
  pipeline: all_up_kuber