apiVersion: v1
kind: Service
metadata:
  name: {{KUBER_LB_NAME}}
  namespace: stand-demo
spec:
  selector:
    app: {{KUBER_DP_NAME}}
  type: LoadBalancer
  externalIPs:
  - {{CLUSTER_IP}}
  ports:
  - name: "rabbit-port"
    protocol: TCP
    port: {{CLUSTER_PORT}}
    targetPort: "rabbit-port"
  - name: "rabbit-m-port"
    protocol: TCP
    port: {{CLUSTER_MANAGEMENT_PORT}}
    targetPort: "rabbit-m-port"