agent_namespace: '{{AGENT_NAMESPACE}}'

agent:
  name: '{{AGENT_NAME}}'
  response_timeout_sec: {{AGENT_RESPONSE_TIMEOUT}}

  pipeline: {
    utterance_annotators: ['ner'],
    skill_selector: ['chitchat_odqa'],
    skills: ['chitchat', 'odqa'],
    response_selector: ['max_confidence'],
    response_annotators: ['ner'],
    response_formatter: ['test_formatter'],
  }

services:
  service:
    batch_size: 5
    infer_timeout_sec: 30

    connector_params:
      formatter: 'formatter'
      caller: 'caller'
      url: 'http://127.0.0.1:5000/answer'

channels: {}

database:
  host: '{{MONGO_HOST}}'
  port: {{MONGO_PORT}}

transport:
  type: '{{TRANSPORT_TYPE}}'

  rabbitmq:
    host: '{{RABBIT_HOST}}'
    port: {{RABBIT_PORT}}
    login: '{{RABBIT_LOGIN}}'
    password: '{{RABBIT_PASSWORD}}'
    virtualhost: '{{RABBIT_VIRTUALHOST}}'
