apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{KUBER_DP_NAME}}
  namespace: stand-demo
spec:
  replicas: {{REPLICAS_NUM}}
  template:
    metadata:
      labels:
        app: {{KUBER_DP_NAME}}
    spec:
      containers:
      - name: "connector"
        image: {{KUBER_IMAGE_TAG}}
        volumeMounts:
        - name: volume-logs
          mountPath: /logs
        - name: volume-podinfo
          mountPath: /etc/podinfo
          readOnly: false
        env:
        - name: MODEL_NAME
          value: "{{CONNECTOR_FULL_NAME}}"
        - name: SERVICE_NAME
          value: "{{SERVICE_NAME}}"
        - name: INSTANCE_ID
          value: "{{INSTANCE_ID}}"
        - name: MODE
          value: "{{MODE}}"
        - name: POD_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumes:
      - name: volume-logs
        persistentVolumeClaim:
          claimName: logs-hostpath-pvc
      - name: volume-podinfo
        downwardAPI:
          items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
        - {{DNS_IP}}
