apiVersion: v1
kind: Service
metadata:
  name: http-proxy-ignatov-lb
spec:
  selector:
    app: http-proxy-ignatov-dp
  type: LoadBalancer
  externalIPs:
  - 10.11.1.251
  ports:
  - name: http-proxy-ignatov
    protocol: TCP
    port: 7051
    targetPort: cp7051